### ISSUE TITLE
Add mechanism to allow mobile site to render as desktop on mobile devices.

### ISSUE THREAD

**Issue by hamishwillee** [ArduPilot/ardupilot_wiki#101]
Some people prefer to browse the desktop site, and there are inconsistencies with browsers on some devices that can mean the mobile version does not render properly. This would provide an additional option in those cases.

**Comment by gmorph** [comment]
This seems to work fairly well for me in the new wiki.  I'm going to close this on the basis that we have gone to a new wiki system and this issue was raised for the previous wiki system.
If this needs to be re-opened we need more details on what the actual issues are.  Note on the android phone and iphone I tested the wiki appears to work great.

**Comment by hamishwillee** [comment]
OK, Works for me.
