### ISSUE TITLE
SITL on Linux Map "Unavailable"

### ISSUE THREAD

**Issue by mehmetyldz87** [ArduPilot/ardupilot_wiki#1092]
I encountered such a problem with map "Unavailable" . How can I solve this problem? Regards Mehmet
![map_001](https://user-images.githubusercontent.com/7778498/36477751-6296cb9a-1713-11e8-90f0-ed58bbb4a718.png)

**Comment by rmackay9** [comment]
This is not really the place to ask support questions but in any case, the issue is the map provider. Go to the top right of the screen and a menu item should appear that allows setting the provider.  I find MicrosoftSatellite works.  Sadly it's not remembered so it needs to be done each time.  I hear from @peterbarker that there is a command line option to set the map provider but I haven't found it.

**Comment by mehmetyldz87** [comment]
Thanks @rmackay9  , I apologize for the inconvenience. I did not hear from this discuss . I opened a topic 

https://discuss.ardupilot.org/t/sitl-on-linux-map-unavailable/26088

**Comment by rmackay9** [comment]
@mehmetyldz87, no troubles!
