### ISSUE TITLE
Edit complete parameters list : broken link

### ISSUE THREAD

**Issue by kikislater** [ArduPilot/ardupilot_wiki#1193]
Hi,
I would like to add this : https://github.com/ArduPilot/ardupilot/issues/7061 to arduplane full parameter wiki but links to edit page is dead. It refers to https://github.com/ArduPilot/ardupilot_wiki/blob/master/plane/source/docs/parameters.rst which does not exists.

Even parameters.rst doesn't exist in  https://github.com/ArduPilot/ardupilot_wiki/tree/master/plane/source/docs

Could you point me where is the file please ?

**Comment by hamishwillee** [comment]
The parameters are generated from source - so you need to edit them in the source tree. 

The link fails because we dynamically generate the wiki parameters at build time - but the theme (which creates the edit link) does not know that this page is not really stored in github. We can create an exception in the theme to make the link go away for this case, but that is low priority.
