### ISSUE TITLE
problem in ardupilot-gazebo-plugin

### ISSUE THREAD

**Issue by mohand150** [ArduPilot/ardupilot_wiki#1233]
I followed the tutorial of the installation of gazebo [](https://github.com/khancyr/ardupilot_gazebo#ardupilot-gazebo-plugin)
![capture du 2018-05-02 17-13-10](https://user-images.githubusercontent.com/34864889/39532722-ab496036-4e2d-11e8-8610-f9e42eed7a96.png)

1st problem  ---> when I run in the 1st terminal `sim_vehicle.py -v ArduCopter -f gazebo-iris -m --mav10 --map --console -I0`,  there is the console and map that come out but there is no data received from the simulator ?
2nd problem ---> the card is white (invailable) how to add the card provider in the script bash ?

**Comment by khancyr** [comment]
hello,
Check on upper on the terminal what cause SITL to crash. 
About blank map : add the following lines to the end of your ”.bashrc” (change MicrosoftHyb by the provider you want):

export MAP_SERVICE="MicrosoftHyb"

This is the documentation section if it is link to some documentation please give us a link where you suspect it is false. Otherwise for use support please use http://discuss.ardupilot.org/.
Thanks
