### ISSUE TITLE
Copter: document Notch filter

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot_wiki#1559]
Copter-3.6 includes a notch filter (parameters are under INS_) so we should add a page for this in the "Advanced Configuration" section of the copter wiki.  It could be include in Plane and Rover as well although it seems unlikely that users would ever use it... perhaps quadplane users would

**Comment by n1ente** [comment]
my vote for this, I want to let you know how much a proper notch filter helped me: its enabling autotune on small copter, because without it, autotune doesn't works cause its constantly confused by the background noise from the imu data, the FC cannot understand when an autotune's twich finish, so pre notch filter era autotune could make only first twich on all our small frame.

**Comment by Hwurzburg** [comment]
closing....we have a page now
