### ISSUE TITLE
external ESC on the CHUCK

### ISSUE THREAD

**Issue by hamelsveld** [ArduPilot/ardupilot_wiki#1615]
Hi,

If I want to use the CHUCK to a X8 frame and connect an external ESC to it (for a motor that needs more power). Can it be done with the CHUCK? and will the rest work out of the box on a bigger frame like the X8?

**Comment by auturgy** [comment]
User support is provided through discuss.ardupilot.org so I’ll close this (sorry - it’s just impossible to track and manage otherwise).
To answer your question, you can assign one of the servo outputs to be throttle. Guidance is in the wiki: 
http://ardupilot.org/copter/docs/common-CHUCK-overview.html
Some features such as DShot and BLHeli telemetry aren’t available on the CHUCK.
