### ISSUE TITLE
clicking on CUAV V5 image leads to 404 error

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot_wiki#2157]
Clicking on the top image on the CUAV V5 plus board produces a Not Found error
http://ardupilot.org/copter/docs/common-cuav-v5plus-overview.html

**Comment by rmackay9** [comment]
Same issue for the holybro durandal: http://ardupilot.org/copter/_images/holybro_durandal/durandal_iso.png

**Comment by Hwurzburg** [comment]
this is due to the fact that the image/target directives are incorrect....
all images in the sources images directory and subdirectories are copied to the subwiki's _images directory....his target path is incorrect....same for all the other subdirectories with CUAV stuff...pages with those images also have incorrect target directives...

**Comment by Hwurzburg** [comment]
fixed
