### ISSUE TITLE
Need to update Schematics repo

### ISSUE THREAD

**Issue by tridge** [ArduPilot/ardupilot_wiki#2174]
We should update the Schematics repo:
https://github.com/ArduPilot/Schematics
with all available schematics for hardware listed on our hw page, then link to the schematic for each board when available.
I also think a single table with a Schematics column would be good, with "Not available" for boards with no schematics

**Comment by Hwurzburg** [comment]
added all schematics for boards that we host pages for, and links on those pages...

I think it will be easier to maintain just adding to board pages as they are created rather than adding another common page with a table that has to be additionally updated when a new board page is added...Randy agrees...
