### ISSUE TITLE
How to check real flight with simulated flight.

### ISSUE THREAD

**Issue by Sneha-hub115** [ArduPilot/ardupilot_wiki#2604]
Hi,
I’m using ubuntu 18.04 to build the px4 code for gazebo and jmavsim using QGround control. I’m stuck with the following issues:

1. How to check real flight with simulated flight using QGround control, gazebo, jmavsim.

Thank you

**Comment by rmackay9** [comment]
@Sneha-hub115,

We have some information here on the wiki re simulators (there are quite a few): https://ardupilot.org/dev/docs/simulation-2.html

To be clear, ArduPilot is software, PX4 is another different type of software that we can't help you with.  Pixhawk is a type of hardware.

This is our wiki to-do list so I'll close this issue because it probably belongs in the developer discuss area or on gitter.  Links to discuss and gitter are on this web page: https://ardupilot.org/copter/docs/common-contact-us.html
