### ISSUE TITLE
Outdated RTK info

### ISSUE THREAD

**Issue by Hwurzburg** [ArduPilot/ardupilot_wiki#3213]
Randy, trying to update the wiki on RTK GPS...need some answers, with my intended actions:

going to add links to F9P update instructions on Holybro RTK and CUAV, and will ask Philip if the mro one needs it since we off-site link for that one...

1. apparently,, the Trimble is no longer made...archive it?(yes)
2. Septentrio is out of date...AsteRx-m is no longer made... remove from page?(yes)
3. JDrones has no GPS products ...remove them from landing page?(yes)
4. Holybro RTK is not mentioned on GPS for YAW page, shall I add it?(yes)
5. Should I add mro RTL link on landing page? (yes)

let me know

**Comment by rmackay9** [comment]
@Hwurzburg

1. No, I think we should instead try and update with a more recent link.  I've ping'd the dev-team channel.
2. No, I think we should leave this one because the company is still around and maybe the same instructions work for newer models.  I'm not a fan of completely removing the page because it means users will assume this company's GPSs do not work with ArduPilot when they probably do.  I'm sure we have users (even core developers) using these GPSs.
3. yes
4. yes please!
5. yes please!

Thanks very much for this

**Comment by khancyr** [comment]
about 2. AsteRx-m2 is not discontinued only the AsteRx-m, so we may remove the mention from AsteRx-m and keep the page for AsteRx-m2

**Comment by rmackay9** [comment]
Great, so for 2, let's just remove the "-m" links from the page.

**Comment by Hwurzburg** [comment]
Yeah that's what I meant in number two

**Comment by Hwurzburg** [comment]
done...closing
