### ISSUE TITLE
DShot/BLHeli pages should mention min, max, trim may be set automatically

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot_wiki#3642]
[A Copter-4.0.7 user](https://discuss.ardupilot.org/t/help-about-using-dshot-on-tail-rotor/73269/4) noticed while setting up DSshot/BLheli that the SERVOx_MIN, MAX, TRIM parameters were being set automatically and they were concerned about this.  We should probably add a note somewhere on this wiki page to tell users that this is expected behaviour. https://ardupilot.org/copter/docs/common-brushless-escs.html

**Comment by Hwurzburg** [comment]
unfortunately the user did not actually read the page about DShot....which has the prominent note:
**When an output is configured for DShot, the SERVOx_MIN/MAX/TRIM parameters for that output will always be ignored since DShot does not use these parameters. The trim value used will be 1500 if it’s a reversible output, or 1000 if normal output setup in DShot, and the output range always be 1000-2000. No ESC calibration step is required.**
