### ISSUE TITLE
Got COMMAND_ACK: GET_HOME_POSITION: FAILED

### ISSUE THREAD

**Issue by HL-Tsai** [ArduPilot/ardupilot_wiki#4461]
I'm working on an indoor automatic flight project, using only optical flow without GPS, and using Raspberry PI 4B to communicate with Pixhawk, and I've used Mission Planner to set up EKF origin, but I still have this problem, so I'd like to ask if there's something I'm missing.
Firmware: ArduCopter V4.2.2
![dddcd77b96b96971465a81e2af12a73f8b7cdc3](https://user-images.githubusercontent.com/101713698/180378364-4fa91f4d-1f10-41c5-99dc-b4f879643c1b.jpeg)

**Comment by rmackay9** [comment]
@HL-Tsai,

If you have an onboard log we can more easily look into this.  I suspect though that the EKF origin hasn't actually been set even though MP has been used to try and set the EKF origin.  e.g. the set of the origin has failed for some reason.  Home isn't set until the EKF origin has been set and the vehicle has a good position estimate (I think).

**Comment by rmackay9** [comment]
Ah, this shouldn't really be here.  This is the wiki issues list so I'll go ahead and close this.  Sorry to be strict but otherwise our to-do lists (which is what this is) become another support forum.

Could you create a new topic in the [Copter-4.2 support forum](https://discuss.ardupilot.org/c/arducopter/copter42/161)?  Sorry for the troubles.
