### ISSUE TITLE
Airbrakes

### ISSUE THREAD

**Issue by markskyyy** [ArduPilot/ardupilot_wiki#4510]
[Airbrakes](https://ardupilot.org/plane/docs/airbrakes-on-plane.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

Hello. I want to setup airbrakes.
I am doing everything like here: https://ardupilot.org/plane/docs/airbrakes-on-plane.html

![001](https://user-images.githubusercontent.com/24563723/184902059-a67c979d-885a-4e23-91f7-5c2b15547ecb.jpg)

But in other windows there is something strange:

![002](https://user-images.githubusercontent.com/24563723/184902267-cd2e1efc-a61f-4389-b398-3a23e71a247d.jpg)
![003](https://user-images.githubusercontent.com/24563723/184902289-aff2d3bd-3a74-4e35-8b9d-41ce6f5354fb.jpg)

And I have an error:

![004](https://user-images.githubusercontent.com/24563723/184902438-4e8275c1-4b37-4924-83d3-b112183b1f43.jpg)

Are airbrakes removed from code?

**Comment by Hwurzburg** [comment]
first, wiki issues is not the place for setup or support questions...very few people look at these....you should post in discuss.ardupilot.org...

that problem is fixed in "latest" but has not been backported to stable versions..it does work in stable but spams that messsage...will bring it up with vehicle maintainer..
