### ISSUE TITLE
Images on Wiki are degraded

### ISSUE THREAD

**Issue by bortek** [ArduPilot/ardupilot_wiki#494]
Have you noticed that images on a Wiki have been severely degraded? This probably has to do with the move to a new site that was done couple of months ago.

Take a look at this page and click on any Mission Planner screenshots. It is not possible see the text on them.

http://ardupilot.org/copter/docs/common-camera-shutter-with-servo.html

**Comment by hamishwillee** [comment]
@bortek Thanks very much. I have updated this particular case with the original image from wordpress.

Yes, this was intentional/known issue. As a "whole" the images were massively higher size and resolution than they needed to be, and much bigger than we could reasonably host on Github or should get people to sync when editing. We therefore decided to reduce them, and in order to make this achievable in the time we did so "largely" as an automated process. 
As a result many images (not all) are of lower quality than previously. In many cases this does not make them unusable. In others, like this one, it does.

So if you spot any others that are unusable then please continue to let us know and I'll see about creating better images. Thanks!
