### ISSUE TITLE
Setting up SITL on Linux

### ISSUE THREAD

**Issue by jhljx** [ArduPilot/ardupilot_wiki#517]
Setting up SITL on Linux - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

And the instruction './autogen.sh --enable-libraries'  couldn't run successfully

**Comment by magicrub** [comment]
Can you provide more information? Perhaps paste here the output of running the command?

**Comment by jhljx** [comment]
After I type the instruction './autogen.sh --enable-libraries' It shows as follows:

processing .
deletefiles is 
Running libtoolize...
Remember to add `AM_PROG_LIBTOOL' to `configure.in'.
You should add the contents of `/usr/local/share/aclocal/libtool.m4' to `aclocal.m4'.
Running aclocal -I .  ...
aclocal: warning: autoconf input should be named 'configure.ac', not 'configure.in'
aclocal: error: couldn't open directory 'm4': No such file or directory

**Error**: aclocal failed. This may mean that you have not
installed all of the packages you need, or you may need to
set ACLOCAL_FLAGS to include "-I $prefix/share/aclocal"
for the prefix where you installed the packages whose
macros were not found

**Comment by magicrub** [comment]
Why are you calling auto gen? For sitl you run sim_vehicle.py from writing
the vehicle folder such as /ArduPlane.

Closing because this is another help question in the wiki bug tracker
system.

On Aug 15, 2016 5:58 AM, "jhljx" <notifications@github.com> wrote:

After I type the instruction './autogen.sh --enable-libraries' It shows as
follows:

processing .
deletefiles is
Running libtoolize...
Remember to add AM_PROG_LIBTOOL' toconfigure.in'.
You should add the contents of /usr/local/share/aclocal/libtool.m4' to
aclocal.m4'.
Running aclocal -I . ...
aclocal: warning: autoconf input should be named 'configure.ac', not '
configure.in'
aclocal: error: couldn't open directory 'm4': No such file or directory

*Error*: aclocal failed. This may mean that you have not
installed all of the packages you need, or you may need to
set ACLOCAL_FLAGS to include "-I $prefix/share/aclocal"
for the prefix where you installed the packages whose
macros were not found

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/ArduPilot/ardupilot_wiki/issues/517#issuecomment-239795371>,
or mute the thread
