### ISSUE TITLE
COM Port is not accessible after firmware installed

### ISSUE THREAD

**Issue by jlt206** [ArduPilot/ardupilot_wiki#5687]
Having had to install the ST Virtual Com Port drivers previously to make a connection to the SpeedyBee F405 v4 Stack for Betaflight and INAV... the only way I have been able to get the Ardupilot firmware installed on the FC is to use the INAV firmware installer, once the FC is placed into DFU mode and flash it with the Copter Firmware (arducopter.hex).

Once installed the Virtual Com Port appears and I am then able to connect using the Mission Planner.

However, if I disconnect the cable for any reason after, I can never get the COM port back and have to go through the same process again.

Pretty frustrating.

Using Windows 11 Pro with Latest Copter Firmware [4.4](https://firmware.ardupilot.org/Copter/stable-4.4.4/speedybeef4v4/) and 
STSW-STM32102 | STM32 Virtual COM Port Driver | 1.5.0

**Comment by Hwurzburg** [comment]
support issues should be here : https://discuss.ardupilot.org/
that said, you when you first install ArduPilot on a controller NOT already having ArduPilot, you should follow the instructions here: https://ardupilot.org/copter/docs/common-loading-firmware-onto-chibios-only-boards.html

most likely cause of your issue is that you did not install the correct firmware with an ArduPilot bootloader....for the SpeedyBee F405 v4 it would be https://firmware.ardupilot.org/Copter/latest/speedybeef4v4/arducopter_with_bl.hex

if you need further assistance try the support forum
