### ISSUE TITLE
Joystick/Gamepad

### ISSUE THREAD

**Issue by bulentkipcak** [ArduPilot/ardupilot_wiki#5779]
Hi, 
I set it up to be able to use the joystick and enabled control with the joystick i can change flight modes and i can arm, disarm  but it doesn't react to throttle and direction controls. When i made the same settings in my windows11 i could use it without any problems but i cannot use it in ubuntu 20.04.6. i am currently using the joystick with QGroundControl without any problems but i cannot use it in mission planner.

when i use the joystick the bars in the menu below react
![Screenshot from 2024-02-10 23-25-30](https://github.com/ArduPilot/ardupilot_wiki/assets/95385514/93711667-e4b0-4b08-8260-888fc5285ef2)

but there is no change in the bars in this menu
![Screenshot from 2024-02-10 23-24-31](https://github.com/ArduPilot/ardupilot_wiki/assets/95385514/97be3bfe-2b7c-4cf4-9f3e-ca31657a0aa1)

i manually changed the rc1 rc2 rc3 rc4 min max parameters
![Screenshot from 2024-02-10 23-33-48](https://github.com/ArduPilot/ardupilot_wiki/assets/95385514/d4b51a4f-904b-4487-8502-cb88478cf1d1)

**Comment by Hwurzburg** [comment]
joystick is NOT RC..its MAVLink override messages....joystick movements will not appear on an RC setup screen....and RCx_MIN-MAX params have no impact on joystick operation...it must  be calibrated using that calibration screen

**Comment by bulentkipcak** [comment]
> joystick is NOT RC..its MAVLink override messages....joystick movements will not appear on an RC setup screen....and RCx_MIN-MAX params have no impact on joystick operation...it must be calibrated using that calibration screen

i did what it said in the documentation

**Comment by bulentkipcak** [comment]
still cannot solved

**Comment by rmackay9** [comment]
Hi @Hwurzburg,

FYI, when using MP once a joystick is enabled it will indeed update on the RC calibration screen.

@bulentkipcak,

I've used this quite recently and it does work so I'm going to close this issue.  By the way, it is best to raise issues in [the support forums](https://discuss.ardupilot.org/c/arducopter/copter-44/169) instead of here which is really our to-do list which is reserved for confirmed bugs and enhancement requests.  Sorry to be strict but otherwise our to-do list turns into another support forum.

**Comment by Hwurzburg** [comment]
@rmackay9 yeah sorry, confused NOT using that cal screen with a joystick to set limits(which you should not do), with it not moving the bars`
