### ISSUE TITLE
Intel Aero Overview

### ISSUE THREAD

**Issue by patrickpoirier51** [ArduPilot/ardupilot_wiki#599]
[Intel Aero Overview](http://ardupilot.org/rover/docs/common-intel-aero-overview.html) - Describe the issue/suggestion and improve the title. Please keep a link to the original article if relevant.

**Comment by patrickpoirier51** [comment]
Some users areporting a discripency between  this page and Intel current release product

**Comment by billbonney** [comment]
I think you will need to provide the corrected details so they can be applied to the page. Raising an issue against the page won't make the information that is the truth appear... sorry

**Comment by patrickpoirier51** [comment]
the intent of  issue is to raise a flag so the information provided is up to date with the actual production board and not related to s preliminary release - if this would be the case after a double check- otherwise  this  issue can be closed

**Comment by magicrub** [comment]
Issue is TODO. We don't have any actionable data, do you?

On Nov 12, 2016 1:08 PM, "patrickpoirier51" <notifications@github.com>
wrote:

the intent of issue is to raise a flag so the information provided is up to
date with the actual production board and not related to s preliminary
release - if this would be the case after a double check- otherwise this
issue can be closed

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ArduPilot/ardupilot_wiki/issues/599#issuecomment-260148478>,
or mute the thread

**Comment by patrickpoirier51** [comment]
Looking at the getting started  pics 
https://software.intel.com/sites/default/files/managed/25/d5/Intel-Aero-Compute-Board-Getting-Started.pdf
We can clearly see the ms5611 on the back as a confirmation that BOM is consistent with production. Issue closed no action required unless you update wiki with the new pictures

**Comment by magicrub** [comment]
Pull requests welcome

**Comment by patrickpoirier51** [comment]
Will do once we receive board
