### ISSUE TITLE
Common Autopilots 

### ISSUE THREAD

**Issue by auturgy** [ArduPilot/ardupilot_wiki#655]
http://ardupilot.org/copter/docs/common-autopilots.html#common-autopilots
needs updating.
I'm happy to do this, but need some background/guidance as to what should/shouldn't be listed.
For instance the CUAV Pixhack is open source, and CUAV is a supporter of Ardupilot, but it isn't listed.
Pixhawk Mini, VRBrain, P9X, Raspilot, BBBMini are also not listed..

**Comment by hamishwillee** [comment]
@rmackay9 @tridge Can you provide the necessary guidance?

**Comment by rmackay9** [comment]
VRBrain, Raspilot, BBBMini could/should all be added.  We just need someone to take responsibility for creating the pages and maintaining them (not that it takes much maintenance).
I don't think the variants of the Pixhawk should be listed (i.e. Pixhack) because they're primarily just a different board layout from the original. Same goes for the Pixhawk Mini.

**Comment by rmackay9** [comment]
For the Pixhawk variants.. one difference is the sensors have been updated.  So perhaps what we could do is add a note at the top of the Pixhawk Overview page to say, "this page covers all the Pixhawk variants including Pixhack, etc".  and then lower down in the Sensors area we provide the list of possible sensors it may be using.  I.e. MPU6k, MPU9250, etc.

**Comment by Hwurzburg** [comment]
This has been done ...closing
