### ISSUE TITLE
QuadPlane Overview

### ISSUE THREAD

**Issue by wazoo22** [ArduPilot/ardupilot_wiki#680]
A suggestion not about the overview but the firmware in general.
Right now the firmware is quite limited, in that it is aimed at a multicopter with a plane grafted into/onto it. There is certainly some interest in this version of the VTOL concept, but seems that some modifications would make the firmware usable for tailsitters as well, and the firmware already goes a fair way toward accomplishing this. The transition is there at least. Tailsitters are so far either multi-engine tractor concepts or twins that are coaxial contrarotating. Neither are covered by this firmware at present, but could be, thereby opening up a fertile field of design that has been sorely neglected, and has great utility and simplicity.  
I personally would support such firmware enthusiastically, with prototyping. I have several already-flying examples, using the KK 2.1.5 board, that really could use some better hardware like the Pixhawk or Pixfalcon, if firmware were available. The coaxial firmware that's in the testing stages in Copter has great merit also, but needs to be compiled, which I can't do, and lacks the transition and functionality as a plane. Can we get these efforts together somehow?

**Comment by rmackay9** [comment]
@wazoo22, this really belongs in the main ardupilot issues list so I'll close this issue here but feel free to raise it again over there.  https://github.com/ArduPilot/ardupilot/issues

By the way, AC3.4 will include binaries for the coax-copter and single-copter.  we're combining a bunch of firmwares together.  The limitation previously was just that our build server was overloaded because we had so many individual frames and boards that we supported.  We still support them all but we've combined many of the binaries together.  AC3.5 should start beta testing before the end of Jan.
