### ISSUE TITLE
Building Arducopter with Arduino

### ISSUE THREAD

**Issue by thjubeck** [ArduPilot/ardupilot_wiki#713]
Hey, 
I am able to compile the base code with arduino ide but after uploading the code the board does not start (CLI not accessable and no lights on board). I can upload pre compiled hex and everything works fine. Anyone have any ideas what could be going wrong?

**Comment by rmackay9** [comment]
It's likely that the software is too big to fit on the AVR but it's really hard to say.  There should be a message if that's the case (i.e. if the firmware is too big for the AVR, a message will be displayed at the end of the upload).

support issues should really be raised in the forums instead of here on the wiki to-do list.  Here's the link: http://discuss.ardupilot.org/c/arducopter

Just need to warn you that we don't support the AVR boards anymore.  They just don't have the CPU power, RAM or flash for all the features we've added over the past 2 years.
