### ISSUE TITLE
installing ardupilot

### ISSUE THREAD

**Issue by padmashree9110** [ArduPilot/ardupilot_wiki#790]
Hi
I am trying to install ardupilot. But when i give command-
git submodule update --init --recursive
Cloning into 'modules/PX4Firmware'...
fatal: unable to connect to github.com:
github.com[0: 192.30.255.112]: errno=Connection timed out
github.com[1: 192.30.255.113]: errno=Connection timed out
fatal: clone of 'git://github.com/ArduPilot/PX4Firmware.git' into submodule path 'modules/PX4Firmware' failed

its getting strucked here only and after long time its showing tym out.
Can someone please help me to resolve this

**Comment by rmackay9** [comment]
Sounds like an issue connecting to the internet or maybe try "git submodule init" followed by "git submodule update --recursive"
I'll close this issue, doesn't really belong on the wiki to-do list in any case.
Here are other ways to contact the developers.  Because you're trying to do development you could pop into one of the gitter channels.
http://ardupilot.org/copter/docs/common-contact-us.html
